spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false
    username: root
    password: qiuyifan
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.example.demo.*
      filtesr: stat wall
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true

  jdbc:
    template:
      query-timeout: 3
  # 配置mybatis规则
  mybatis:
#    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true